#!/bin/bash
CLEAN="clean"
BUILD="build"
if [ "$1" == "-u" ]; then
  CLEAN=""
  BUILD=""
fi
./gradlew -Pmini -Pmain=main_wheel_test.py -Pexclude=light.*,sonar.*,wheel_calibrator.py $CLEAN $BUILD upload
